version: 0.2
phases:
  install:
    runtime-versions:
      docker: latest
    commands:
      - echo Downloading kubectl...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.12/2020-07-08/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - echo Generating kubeconfig...
      - mkdir ~/.kube
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $CLUSTER_NAME
  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 7)
      - aws codeguru-reviewer create-code-review --name SAST_$COMMIT_HASH --repository-association-arn arn:aws:codeguru-reviewer:ap-southeast-2:291533180773:association:042ebef3-a354-4558-b193-d23898b06c53 --type RepositoryAnalysis={RepositoryHead={BranchName=main}}
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - AWS_ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:$COMMIT_HASH
      - docker build -t $AWS_ECR_URI .
      - docker push $AWS_ECR_URI
  post_build:
    commands:
      - echo Deploying new pod...
      - sed -i.bak 's#AWS_ECR_URI#'"$AWS_ECR_URI"'#' ./deployment.yaml
      - kubectl apply -f ./deployment.yaml
