apiVersion: v1
kind: Service
metadata:
  name: sample-spring-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: sample-spring-backend
  type: NodePort
  ports:
    - port: 8080 
      targetPort: 8080
      protocol: TCP
